config/routes.rb
Rails.application.routes.draw do
  resources :postulations, only: [:index, :create, :update]
  resources :posts
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:new, :create]

  get 'home/index'
  get 'home/jobs'
  root "home#index"
end

app/models/post.rb
class Post < ApplicationRecord

    # Validaciones
    validates :titulo, presence: true
    validates :descripcion, presence: true
    validates :estado, presence: true

    # Enums
    enum estado: [:borrador, :publicada, :terminada]

    scope :publicadas, -> { where(estado: :publicada) }
    scope :borradores, -> { where(estado: :borrador) }
    scope :terminadas, -> { where(estado: :terminada) }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    if current_user.role == "admin"
      @posts = Post.all
    else
      @posts = Post.publicadas
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:titulo, :descripcion, :estado)
    end

    def authenticate_admin
      unless current_user && current_user.role == "admin"
        redirect_to root_path, alert: "No tienes permisos para acceder a esta página."
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.select :estado, Post.estados.keys %>
  </div>

  <br />
  <div>
    <%= form.submit "Enviar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>ID Publicacion:</strong>
    <%= post.id %>
  </p>
  <p>
    <strong>Titulo:</strong>
    <%= post.titulo %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= post.descripcion %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= post.estado %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editar publicación</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Ver", @post %> |
  <%= link_to "Volver", posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Nueva Publicación</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Ver Publicación", post, class: "btn btn-primary" %>
    </p>
  <% end %>
</div>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to "Nueva Publicación", new_post_path, class: "btn btn-primary" %>
<% end %>

app/views/posts/new.html.erb
<h1>Nueva Publicación</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Volver", posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <%= button_to "Postular", postulations_path(post_id: @post.id), method: :post, class: "btn btn-primary" %>
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to "Editar", edit_post_path(@post), class: "btn btn-primary my-1" %> 
    <%= button_to "Eliminar", @post, method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn-danger my-1" %>
  <% end %>
  <%= link_to "Volver", posts_path, class: "btn btn-primary" %> 
</div>